### PR TITLE
CI GitHub Action

### PR DESCRIPTION
**Pull request by JohnTrapp**
This action will run flake8 and provide continuous integration.

### CODE REVIEW

**Comment by JohnTrapp** [comment]
@adamtrapp, ready for review!

**Comment by adamtrapp** [comment]
So this code is for updating pypi when we make a new tag, and also implementing a testing thing?

**Comment by JohnTrapp** [comment]
This won't update pypi. It'll just run flake8, which checks formatting. Pypi will be in a different P.R.

**Comment by adamtrapp** [comment]
Ok! Looks good, then.

**Review by adamtrapp — APPROVED** [review]
LGTM :+1:

**Pull request merged**
